### PR TITLE
Got a constructor working in WASM glue.

### PR DESCRIPTION
**Pull request by Redrield**
Added a reset button to the emulator frontend.

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
That's great - thanks for contributing

**Comment by ColinEberhardt** [comment]
@Redrield I've rolled back this PR as I have been struggling to get it to build. The initial failure was:

```
$ make
Makefile:5: *** missing separator.  Stop.
```

Changing the spaces to tabs in the makefile fixed this, but resulted in a new failure:

```
$ make
error: failed to run `rustc` to learn about target-specific information
```

I'm new to all of this, so would appreciate some help!

**Comment by Redrield** [comment]
@ColinEberhardt Strange that doesn't work. Here's a Makefile that _does_ work, though it also assumes that wasm-gc has already been installed on the machine running it.

```
all:
	@cargo build --target=wasm32-unknown-unknown --release
	@wasm-gc target/wasm32-unknown-unknown/release/emulator.wasm web/emulator.wasm
```

**Comment by Redrield** [comment]
The only other difference is that the cargo project that I have it in is called emulator, so it should be a simple fix to change that.

**Pull request merged**
